import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProtectedContent from "@/layouts/ProtectedContent";
import { AuthProvider } from "@/contexts/AuthContext";
import { ClientLayoutWrapper } from "@/layouts/ClientLayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProtectedContent>
            <div className="min-h-screen bg-gray-900/20 text-white">
              <ClientLayoutWrapper>
                {children}
              </ClientLayoutWrapper>
            </div>
          </ProtectedContent>
        </AuthProvider>
      </body>
    </html>
  );
}